### ISSUE TITLE
arxiv chat follow up

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#116]
I posted it on reddit r/physics and there was one guy that said that it was returning "non-relevant" results (can't share the link cause the post has been taken down now). so let's tackle that first. I think we can begin by comparing the output of arxiv's search bar with our app and see if they don't match

**Comment by bryannho** [comment]
I think we might achieve the most relevant results by removing the category classification altogether. Since Arxiv seems to handle very specific searches quite well, it might just be better to simplify the user's query and pass it directly to Arxiv rather than bothering with topic classification at all. Let me know if you think I should try this @edublancas

**Comment by edublancas** [comment]
ok yeah let's try it.

as a follow up, we should build the "ask questions to the paper" feature. once a user asks for more details about a paper that should become our context, then we can download the HTML version of the paper and then questions can be asked about its contents.

there are a few considerations:

- we need to chunk the paper because it won't fit in the model's context (perhaps by section)
- then we need to do vector search, we can use Scipy's KDTree [example](https://github.com/ploomber/doc/blob/main/notebooks/rag-from-scratch.ipynb)
- there's an [example here](https://github.com/ploomber/doc/blob/main/notebooks/document-qa-basic.ipynb)
- the HTML feature of arxiv is experimental so I'm unsure if this will work, alternatively, we can use the PDF and run OCR, the example above shows how to do it

**Comment by bryannho** [comment]
Okay I can get started on that, will let you know if I run into any issues. Some notes:
- We'll have to retain some overall state so that once a user goes deep into one article, they can switch to another and the model will remember which article they're talking about. As long as the model knows where it can find the article, it can then go and fetch the detailed information.
- The arxiv API also allows [downloading the source TAR file](https://lukasschwab.me/arxiv.py/arxiv.html#Result.download_source) which might be helpful
- Another helpful feature might be altering the sort criteria for the search. Right now we search Arxiv by most relevant articles at all times, but if the user says "show me the most recent cryptography papers" it should search by last updated/submitted

**Comment by edublancas** [comment]
fixed by https://github.com/ploomber/doc/pull/119
