### ISSUE TITLE
document custom project names

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#85]
i see that the custom project name appears now: 

![image](https://github.com/ploomber/doc/assets/989250/5c483054-0c02-4ca2-824b-a598390a579f)

but we don't have documentation

**Comment by bryannho** [comment]
@edublancas custom project names are mentioned as a paid feature in the [pricing overview](https://docs.cloud.ploomber.io/en/latest/pricing/overview.html#ploomber-cloud-professional) but not anywhere else.

since it's a paid feature, I don't think it would be appropriate to document in the [quickstart guide](https://docs.cloud.ploomber.io/en/latest/quickstart/app.html), but there doesn't seem to be another place to put it.

I also noticed we haven't documented the `labels` option either. Maybe we could a new page, `Identifying project`, where we document the custom project name and labels feature? I'll add a note that mentions that custom names is a `paid` feature

**Comment by edublancas** [comment]
I think the project name can be documented here: https://docs.cloud.ploomber.io/en/latest/user-guide/custom-domains.html

we can rename the function to: Custom domains/subdomains

changing the project name changes the x portion in `x.ploomberapp.io`


for the labels, we can create a new "Managing apps" section in the user guide and explain that labels can help you organize and identify your apps

**Comment by bryannho** [comment]
@edublancas whoops forgot to mention this issue in the PR #103 , this issue has been addressed so you can close it now
